library(stringr)

#' checkif_member
#' 
#' for internal use only
#'
#' @param login Drupal login csv
#' @param im institutional membership table
#'
#' @return a factor set
checkif_member <- function(login, im) {
  login$Institution <- str_replace_all(login$Institution, "[[:punct:]]", "")
  login$Institution[login$Institution==""] <- NA # When the above line leaves nothing left, turn "" to NA
  im$drupal <- str_replace_all(im$drupal, "[[:punct:]]", "")

  login$Institution <- str_remove(login$Institution, " UNIVERSITY$")
  login$Institution <- str_remove(login$Institution, "^UNIVERSITY OF ")
  login$`Name/Email` <- str_extract(login$`Name/Email`, "[a-zA-Z0-9]+\\.edu$")
  
  institution_match <- unlist(lapply(login$Institution, function(x, name) {
    match <- str_which(name, paste0("^", x, "$"))
    if (length(match)==0) return(NA)
    return(match)
  }, str_to_upper(im$drupal))) # Need str_to_upper because we uppercase in the Rmd
  
  email_match <- unlist(lapply(login$`Name/Email`, function(x, domain) {
    match <- str_which(domain, paste0(x, "$"))
    if (length(match)==0) return(NA) 
    return(match[1])
  }, str_to_lower(im$drupal)))
  
  matches <- dplyr::coalesce(institution_match, email_match)
  matches <- factor(matches, levels = 1:nrow(im), labels = im$canonical)
  return(matches)
}

#' member_regexp
#' 
#' 
#'
#' @param affiliations list of affiliations generated by deposit_affiliations()
#' @param im institutional membership tibble
#'
#' @return a factor vector of matches
member_regexp <- function(affiliations, im) {
  # Run all the depositor affiliations against a regex of institutional members
  regex <- paste0("\\b(?:", paste(im$regexp, collapse="|"), ")\\b")
  matches <- lapply(affiliations, function(x, regex) {
    matches <- stringr::str_extract(x, regex)
    dplyr::first(na.omit(matches))
  }, regex)

  matches <- unlist(lapply(matches, function(x, im) {
    if (is.na(x)) return(NA)
    im$canonical[as.vector(!is.na(str_match(im$regexp, x)))]
  }, im))
  
  factor(matches, levels=im$canonical, labels=im$canonical)
}

