library(stringr)

#' member_regexp
#' 
#' Use regexp to detect institutional members from free-form fields
#'
#' @param affiliations list of affiliations (i.e. generated by `deposit_affiliations()`)
#' @param im institutional membership tibble
#'
#' @return a factor vector of matches
member_regexp <- function(affiliations, im) {
  
  # Run all the depositor affiliations against a regex of institutional members
  regex <- paste0("\\b(?:", paste(im$regexp, collapse="|"), ")\\b")
  matches <- lapply(affiliations, function(x, regex) {
    if (is.vector(x)) x <- paste(x, collapse=" ")
    matches <- stri_extract_all_regex(x, regex, case_insensitive=TRUE)
    #matches <- stringr::str_extract(fixed(x, ignore_case), regex,)
    dplyr::first(na.omit(matches))
  }, regex)

  matches <- lapply(matches, function(x, im) {
    match <- im$canonical[as.vector(!is.na(stri_extract_first_regex(im$regexp, x, case_insensitive=TRUE)))]
    if (length(match)==0) return(NA)
    match[1] # Only grabbing the first match to make sure the vector length stays the same
  }, im)
  
  factor(unlist(matches), levels=im$canonical, labels=im$canonical)
}

#' checkif_member
#' 
#' for internal use only
#'
#' @param login Drupal login csv
#' @param im institutional membership table
#'
#' @return a factor set
checkif_member <- function(login, im) {
  login$Institution[login$Institution==""] <- NA # When the above line leaves nothing left, turn "" to NA
  #im$drupal <- str_replace_all(im$drupal, "[[:punct:]]", "")
  
  institution_match <- member_regexp(login$Institution, im)
  
  login$`Email` <- str_extract(login$`Email`, "[a-zA-Z0-9]+\\.edu$")
  email_match <- unlist(lapply(login$`Email`, function(x, domain) {
    match <- str_which(domain, paste0("^", x, "$"))
    if (length(match)==0) return(NA) 
    return(match[1])
  }, str_to_lower(im$domain)))
  email_match <- factor(email_match, levels = 1:nrow(im), labels = im$canonical)
  
  
  matches <- dplyr::coalesce(institution_match, email_match)
  return(matches)
}
