on: 
  workflow_dispatch:
    inputs:
      extend_im:
        description: 'Prospective institutional member'     
        required: FALSE
        
name: Render metrics-reports

jobs:
  render:
    name: Render metrics-reports 
    runs-on: ubuntu-latest
    env:
      EXTERNAL_GH_FOLDER: ${{ secrets.EXTERNAL_GH_FOLDER }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install debian packages
        run: sudo apt install libcurl4-openssl-dev texlive-latex-recommended
      - name: Install rmarkdown
        env:
          R_COMPILE_AND_INSTALL_PACKAGES: never
        run: Rscript -e 'install.packages(c("curl", "zoo", "httr", "readr", "tidyr", "dplyr", "ggplot2", "ggfortify", "rmarkdown"))'
      - name: Download private Drupal data
        env:
          EXTERNAL_GH_TOKEN: ${{ secrets.EXTERNAL_GH_TOKEN }}
        run: |
          git clone "https://$EXTERNAL_GH_TOKEN@github.com/QualitativeDataRepository/$EXTERNAL_GH_FOLDER"
      - name: Render documents
        env:
          DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }}
          extend_im: ${{ github.event.inputs.extend_im }}
        run: Rscript -e 'rmarkdown::render("metrics_report.Rmd", "all", output_dir=Sys.getenv("EXTERNAL_GH_FOLDER"))'
      - name: Commit results
        run: |
          cd $EXTERNAL_GH_FOLDER
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add metrics_report.*
          git commit -am "$(date)"
          git push