on: 
  workflow_dispatch:
    inputs:
      extend_im:
        description: 'Prospective institutional member'     
        required: FALSE
      period_begin:
        description: 'Period beginning date (YYYY-MM_DD)'
        required: FALSE
      period_end:
        description: 'Period ending date (YYYY-MM-DD'
        required: FALSE

name: Render metrics-reports

jobs:
  render:
    name: Render metrics-reports 
    runs-on: ubuntu-latest
    env:
      EXTERNAL_GH_FOLDER: ${{ secrets.EXTERNAL_GH_FOLDER }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install extra LaTeX packages
        run: sudo apt install texlive-latex-recommended
      - name: Clone private data repository
        env:
          EXTERNAL_GH_TOKEN: ${{ secrets.EXTERNAL_GH_TOKEN }}
        run: |
          git clone "https://$EXTERNAL_GH_TOKEN@github.com/QualitativeDataRepository/$EXTERNAL_GH_FOLDER"
      - name: Render documents
        env:
          DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }}
          extend_im: ${{ github.event.inputs.extend_im }}
          period_begin: ${{ github.event.inputs.period_begin }}
          period_end: ${{ github.event.inputs.period_end }}
        run: Rscript -e 'rmarkdown::render("metrics_report.Rmd", "all", output_dir=Sys.getenv("EXTERNAL_GH_FOLDER"))'
      - name: Commit results
        run: |
          cd $EXTERNAL_GH_FOLDER
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -am "$(date)"
          git push